import { resolve } from 'path';
import { defineConfig } from 'vite';

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        linear: resolve(__dirname, 'linear/index.html'),
        vercel: resolve(__dirname, 'vercel/index.html'),
        stripe: resolve(__dirname, 'stripe/index.html'),
        framer: resolve(__dirname, 'framer/index.html'),
        airtable: resolve(__dirname, 'airtable/index.html'),
        apple: resolve(__dirname, 'apple/index.html'),
        cal: resolve(__dirname, 'cal/index.html'),
        clickhouse: resolve(__dirname, 'clickhouse/index.html'),
        composio: resolve(__dirname, 'composio/index.html'),
        cursor: resolve(__dirname, 'cursor/index.html'),
        expo: resolve(__dirname, 'expo/index.html'),
        figma: resolve(__dirname, 'figma/index.html'),
        hashicorp: resolve(__dirname, 'hashicorp/index.html'),
        ibm: resolve(__dirname, 'ibm/index.html'),
        intercom: resolve(__dirname, 'intercom/index.html'),
        lovable: resolve(__dirname, 'lovable/index.html'),
        meta: resolve(__dirname, 'meta/index.html'),
        mintlify: resolve(__dirname, 'mintlify/index.html'),
        miro: resolve(__dirname, 'miro/index.html'),
        notion: resolve(__dirname, 'notion/index.html'),
        nvidia: resolve(__dirname, 'nvidia/index.html'),
        'opencode.ai': resolve(__dirname, 'opencode.ai/index.html'),
        pinterest: resolve(__dirname, 'pinterest/index.html'),
        posthog: resolve(__dirname, 'posthog/index.html'),
        raycast: resolve(__dirname, 'raycast/index.html'),
        resend: resolve(__dirname, 'resend/index.html'),
        sanity: resolve(__dirname, 'sanity/index.html'),
        sentry: resolve(__dirname, 'sentry/index.html'),
        shopify: resolve(__dirname, 'shopify/index.html'),
        supabase: resolve(__dirname, 'supabase/index.html'),
        superhuman: resolve(__dirname, 'superhuman/index.html'),
        theverge: resolve(__dirname, 'theverge/index.html'),
        voltagent: resolve(__dirname, 'voltagent/index.html'),
        warp: resolve(__dirname, 'warp/index.html'),
        webflow: resolve(__dirname, 'webflow/index.html'),
        wired: resolve(__dirname, 'wired/index.html'),
        zapier: resolve(__dirname, 'zapier/index.html'),
        claude: resolve(__dirname, 'claude/index.html'),
        cohere: resolve(__dirname, 'cohere/index.html'),
        elevenlabs: resolve(__dirname, 'elevenlabs/index.html'),
        minimax: resolve(__dirname, 'minimax/index.html'),
        'mistral.ai': resolve(__dirname, 'mistral.ai/index.html'),
        ollama: resolve(__dirname, 'ollama/index.html'),
        replicate: resolve(__dirname, 'replicate/index.html'),
        'together.ai': resolve(__dirname, 'together.ai/index.html'),
        'x.ai': resolve(__dirname, 'x.ai/index.html'),
        binance: resolve(__dirname, 'binance/index.html'),
        coinbase: resolve(__dirname, 'coinbase/index.html'),
        kraken: resolve(__dirname, 'kraken/index.html'),
        mastercard: resolve(__dirname, 'mastercard/index.html'),
        revolut: resolve(__dirname, 'revolut/index.html'),
        wise: resolve(__dirname, 'wise/index.html'),
        bmw: resolve(__dirname, 'bmw/index.html'),
        bugatti: resolve(__dirname, 'bugatti/index.html'),
        ferrari: resolve(__dirname, 'ferrari/index.html'),
        lamborghini: resolve(__dirname, 'lamborghini/index.html'),
        renault: resolve(__dirname, 'renault/index.html'),
        tesla: resolve(__dirname, 'tesla/index.html'),
        uber: resolve(__dirname, 'uber/index.html'),
        airbnb: resolve(__dirname, 'airbnb/index.html'),
        starbucks: resolve(__dirname, 'starbucks/index.html'),
        spotify: resolve(__dirname, 'spotify/index.html'),
        spacex: resolve(__dirname, 'spacex/index.html'),
        playstation: resolve(__dirname, 'playstation/index.html'),
        nike: resolve(__dirname, 'nike/index.html'),
        vodafone: resolve(__dirname, 'vodafone/index.html'),
        clay: resolve(__dirname, 'clay/index.html'),
      },
    },
  },
});
